version: '3.8'

services:
  vitivinicultura-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia o diretório atual para o container (opcional para desenvolvimento)
