version: '3.8'

services:
  vitivinicultura-api:
    image: python:3.12-slim
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia o diretório atual para o container (útil para desenvolvimento)
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
